spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobscheduler
    username: admin
    password: secret
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  quartz:
    job-store-type: jdbc

    jdbc:
      initialize-schema: never

    properties:
      org:
        quartz:
          scheduler:
            instanceName: JobScheduler
            

          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: qrtz_
            isClustered: false

          threadPool:
            threadCount: 5
            
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer